image: python:3.13

stages:
  - test
  - build
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-dev python3-pip curl
  # Install uv
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - export PATH="$HOME/.local/bin:$PATH"
  # Setup project with uv
  - uv sync --extra dev
  - touch gencove/tests/.env

test_windows:
  stage: test
  tags:
    - saas-windows-medium-amd64
  variables:
    PYTHON_VERSION_MAJOR: "3"
    PYTHON_VERSION_MINOR: "10"
    PYTHON_VERSION_PATCH: "11"
  before_script:
    - powershell -Command "Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1; refreshenv"
    - powershell -Command "choco install python -y --allow-downgrade --version $env:PYTHON_VERSION_MAJOR.$env:PYTHON_VERSION_MINOR.$env:PYTHON_VERSION_PATCH"
    # Install uv on Windows
    - powershell -Command "irm https://astral.sh/uv/install.ps1 | iex"
    - powershell -Command "uv sync"
    - powershell -Command "New-Item -ItemType File -Path 'gencove/tests/.env' -Force"
  script:
    - powershell -Command "uv run gencove --version"

python39_api_key:
  image: python:3.9
  stage: test
  script: uv run tox -e py39-api_key
  except:
    - tags

python39_user_pass:
  image: python:3.9
  stage: test
  script: uv run tox -e py39-user_pass
  except:
    - tags

python310_api_key:
  image: python:3.10
  stage: test
  script: uv run tox -e py310-api_key
  except:
    - tags

python310_user_pass:
  image: python:3.10
  stage: test
  script: uv run tox -e py310-user_pass
  except:
    - tags

python311_api_key:
  image: python:3.11
  stage: test
  script: uv run tox -e py311-api_key
  except:
    - tags

python311_user_pass:
  image: python:3.11
  stage: test
  script: uv run tox -e py311-user_pass
  except:
    - tags

python312_api_key:
  image: python:3.12
  stage: test
  script: uv run tox -e py312-api_key
  except:
    - tags

python312_user_pass:
  image: python:3.12
  stage: test
  script: uv run tox -e py312-user_pass
  except:
    - tags

python313_api_key:
  image: python:3.13
  stage: test
  script: uv run tox -e py313-api_key
  except:
    - tags

python313_user_pass:
  image: python:3.13
  stage: test
  script: uv run tox -e py313-user_pass
  except:
    - tags

black:
  stage: test
  script: uv run tox -e black_checker
  except:
    - tags

flake8:
  stage: test
  script: uv run tox -e flake8
  except:
    - tags

pylint:
  stage: test
  script: uv run tox -e pylint
  except:
    - tags

bandit:
  stage: test
  script: uv run tox -e bandit
  except:
    - tags

build_docs_stage:
  stage: deploy
  trigger:
    project: gencove/docs-main
    branch: master
  only:
    - master

build_docs_prod:
  stage: deploy
  trigger:
    project: gencove/docs-main
    branch: production
  only:
    - prod

production:
  stage: deploy
  script:
    # Install AWS CLI with uv
    - uv tool install awscli
    # Build package with uv
    - uv build
    # Publish to PyPI with uv
    - uv publish
    # Autotag
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git remote add api-origin https://gencove-deploy-bot:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - export CURRENT_VERSION="$(./version-01-upgrade.sh print | tail -1)"
    - git tag -a "$CURRENT_VERSION" -m "Auto-Release"
    - git push api-origin "$CURRENT_VERSION"
  only:
    # - tags
    #
    # SemVer-compliant tags (with no metadata)
    # - /^v?\d+\.\d+\.\d+$/
    - prod
