before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip python3 python3-dev python3-pip
  # Install dev requirements
  - pip install -r requirements.txt
  # Setup package and it's requirements
  - pip install -e .

python2:
  image: python:2.7
  stage: test
  script: tox -e py27

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

black:
  image: python:3.7
  stage: test
  script: tox -e black

flake8:
  image: python:3.7
  stage: test
  script: tox -e flake8

pylint:
  image: python:3.7
  stage: test
  script: tox -e pylint

bandit:
  image: python:3.7
  stage: test
  script: tox -e bandit

staging:
  script:
    # Generate documentation
    - cd docs && make html
    # Install twine for uploading to pypi
    - pip install twine
    # Upload to pypi
    - python setup.py sdist
    - python setup.py bdist_wheel --universal
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - master
  
production:
  script:
    # Generate documentation
    - cd docs && make html
    # Install twine for uploading to pypi
    - pip install twine
    # Upload to pypi
    - python setup.py sdist
    - python setup.py bdist_wheel --universal
    - twine upload dist/*
  only:
    # - tags
    #
    # SemVer-compliant tags (with no metadata)
    - /^v?\d+\.\d+\.\d+$/
