stages:
  - test
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip python3 python3-dev python3-pip
  - pip install --upgrade 'setuptools<45'
  # Install dev requirements
  - pip install -r requirements.txt
  # Setup package and it's requirements
  - pip install -e .
  # Generate documentation
  - cd docs && make html && cd ..
  # For AWS
  - pip install awscli

python2:
  image: python:2.7
  stage: test
  script: tox -e py27
  except:
    - tags

python37:
  image: python:3.7
  stage: test
  script: tox -e py37
  except:
    - tags

black:
  image: python:3.7
  stage: test
  script: tox -e black_checker
  except:
    - tags

flake8:
  image: python:3.7
  stage: test
  script: tox -e flake8
  except:
    - tags

pylint:
  image: python:3.7
  stage: test
  script: tox -e pylint
  except:
    - tags

bandit:
  image: python:3.7
  stage: test
  script: tox -e bandit
  except:
    - tags

staging:
  stage: deploy
  script:
    # # Install twine for uploading to pypi
    # - pip install twine
    # Upload docs
    - aws s3 sync docs/build/html/ s3://$BUCKET_STAGING/cli/ --delete --region us-east-1
    # Enable the aws cloudfront command
    - aws configure set preview.cloudfront true
    # Clear web cache
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_STAGING --paths "/*"
    # # Upload to pypi
    # - python setup.py sdist
    # - python setup.py bdist_wheel --universal
    # - twine upload dist/*
  only:
    - master
  
production:
  stage: deploy
  script:
    # Install twine for uploading to pypi
    - pip install twine
    # Upload docs
    - aws s3 sync docs/build/html/ s3://$BUCKET_PRODUCTION/cli/ --delete --region us-east-1
    # Enable the aws cloudfront command
    - aws configure set preview.cloudfront true
    # Clear web cache
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_PRODUCTION --paths "/*"
    # Upload to pypi
    - python setup.py sdist
    - python setup.py bdist_wheel --universal
    - twine upload dist/*
    # Autotag
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git remote add api-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - export CURRENT_VERSION="$(./version-01-upgrade.sh print | tail -1)"
    - git tag -a "$CURRENT_VERSION" -m "Auto-Release"
    - git push api-origin "$CURRENT_VERSION"
  only:
    # - tags
    #
    # SemVer-compliant tags (with no metadata)
    # - /^v?\d+\.\d+\.\d+$/
    - prod
