site_name: Gencove Base CLI
site_url: https://docs.gencove.com/cli/

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  custom_dir: docs/overrides
  favicon: img/favicon.ico
  logo: img/iso-gencove@2x.svg
  font:
    text: Inter
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: gencove
      primary: blue
      accent: blue


plugins:
  - search
  - redirects:
      redirect_maps:
        index.md: main.md
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            annotations_path: brief
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            heading_level: 1


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - mkdocs-click
  - pymdownx.details
  - pymdownx.tabbed
  - def_list
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - CLI: main.md
  - Support: support.md
  - Gencove homepage: https://gencove.com
  - Gencove Base docs: /
  - Gencove Explorer docs: /explorer-sdk

extra_css:
  - stylesheets/extra.css
